smiles-columns = [smiles]
num-workers = 4
batch-size = 32
accelerator = cpu
devices = 1
data-path = [reports/hpo/2026-01-28_050157_stage2_hpo_scaffold_seed11/trial_018/chemprop_input.csv]
output-dir = reports/hpo/2026-01-28_050157_stage2_hpo_scaffold_seed11/trial_018/models/chemprop_dmnn
message-hidden-dim = [200]
depth = [5]
dropout = 0.15207586681390686
target-columns = [y]
splits-column = split
task-type = classification
metrics = [prc, roc]
tracking-metric = prc
warmup-epochs = 2
init-lr = 0.0005843105994354612
max-lr = 0.002058543137801626
final-lr = 0.0005140606322538173
epochs = 80
patience = 10
data-seed = 42
pytorch-seed = 42
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
aggregation = norm
aggregation-norm = 100
activation = RELU
ffn-hidden-dim = 300
ffn-num-layers = 1
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
v-kl = 0.0
eps = 1e-08
alpha = 0.1
min-delta = 0.0
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
